version: '3.9'
services:
  hrms-api:
    build:
      context: ./src/HRMS.api  # The path to the project directory
      dockerfile: Dockerfile
    volumes:
      - ./src/HRMS.api:/src/HRMS.api  # Mount the project directory
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development